[package]
name = "rsa-encryption"
version = "0.1.0"
authors = ["Tyler <tylersmaldonado@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
base64 = "0.12.3"
colored = "2"
num = "0.3.0"